// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PriceAggregator.Api.Data;

#nullable disable

namespace PriceAggregator.Api.Migrations
{
    [DbContext(typeof(PriceAggregatorContext))]
    [Migration("20230723162113_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("PriceAggregator.Api.Models.Price", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<decimal>("Close")
                        .HasColumnType("TEXT")
                        .HasColumnName("close");

                    b.Property<int>("FromCurrency")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fromcurrency");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("startdatetime");

                    b.Property<int>("ToCurrency")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tocurrency");

                    b.HasKey("Id");

                    b.ToTable("prices");
                });
#pragma warning restore 612, 618
        }
    }
}
