// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PriceAggregator.Api.Data;

#nullable disable

namespace PriceAggregator.Api.Migrations
{
    [DbContext(typeof(PriceAggregatorContext))]
    partial class PriceAggregatorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("PriceAggregator.Api.Models.Price", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Close")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("close");

                    b.Property<int>("FromCurrency")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fromcurrency");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp");

                    b.Property<int>("ToCurrency")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tocurrency");

                    b.HasKey("Id");

                    b.ToTable("prices");
                });
#pragma warning restore 612, 618
        }
    }
}
